// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOnhUZm4EXzNxOd5sbjjf0BmyU2fyUzlw',
    appId: '1:158170322281:web:8d23cd7ab3818be9db99f8',
    messagingSenderId: '158170322281',
    projectId: 'find-me-cf925',
    authDomain: 'find-me-cf925.firebaseapp.com',
    databaseURL: 'https://find-me-cf925-default-rtdb.firebaseio.com',
    storageBucket: 'find-me-cf925.appspot.com',
    measurementId: 'G-THLX0C1X6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYF0dMVYbdxaUMaAdQ9OfnZ9OVUAhbjnU',
    appId: '1:158170322281:android:639f7a060ece9bdcdb99f8',
    messagingSenderId: '158170322281',
    projectId: 'find-me-cf925',
    databaseURL: 'https://find-me-cf925-default-rtdb.firebaseio.com',
    storageBucket: 'find-me-cf925.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvOcS04t0r9m0gi4tIdpYAiVqMd_v3miw',
    appId: '1:158170322281:ios:e93f6209b57af944db99f8',
    messagingSenderId: '158170322281',
    projectId: 'find-me-cf925',
    databaseURL: 'https://find-me-cf925-default-rtdb.firebaseio.com',
    storageBucket: 'find-me-cf925.appspot.com',
    iosClientId: '158170322281-ak5n70iv2q16nl7mq9dr62kahbllj483.apps.googleusercontent.com',
    iosBundleId: 'com.findme.findmeproject',
  );
}
